<div class="card-body">
	<dl class="row">
		<dt class="col-sm-3">ID:</dt>
		<dd class="col-sm-9">${showcaseMemberProfile.id}</dd>
		<dt class="col-sm-3">会员编码:</dt>
		<dd class="col-sm-9">${showcaseMemberProfile.memberNo}</dd>
		<dt class="col-sm-3">用户名:</dt>
		<dd class="col-sm-9">${showcaseMemberProfile.username}</dd>
		<dt class="col-sm-3">昵称:</dt>
		<dd class="col-sm-9">${showcaseMemberProfile.nickname}</dd>
		<dt class="col-sm-3">个性签名:</dt>
		<dd class="col-sm-9">${showcaseMemberProfile.dailyWords}</dd>
		<dt class="col-sm-3">头像:</dt>
		<dd class="col-sm-9">${showcaseMemberProfile.profilePhoto}</dd>
		<dt class="col-sm-3">邮箱认证:</dt>
		<dd class="col-sm-9">${showcaseMemberProfile.emailStatus.message()}</dd>
		<dt class="col-sm-3">手机认证:</dt>
		<dd class="col-sm-9">${showcaseMemberProfile.mobileNoStatus.message()}</dd>
		<dt class="col-sm-3">实名认证:</dt>
		<dd class="col-sm-9">${showcaseMemberProfile.realNameStatus.message()}</dd>
		<dt class="col-sm-3">安全问题设置状态:</dt>
		<dd class="col-sm-9">${showcaseMemberProfile.secretQaStatus}</dd>
		<dt class="col-sm-3">发送短信:</dt>
		<dd class="col-sm-9">${showcaseMemberProfile.smsSendStatus.message()}</dd>
		<dt class="col-sm-3">客户经理:</dt>
		<dd class="col-sm-9">${showcaseMemberProfile.manager}</dd>
		<dt class="col-sm-3">经纪人:</dt>
		<dd class="col-sm-9">${showcaseMemberProfile.broker}</dd>
		<dt class="col-sm-3">邀请人:</dt>
		<dd class="col-sm-9">${showcaseMemberProfile.inviter}</dd>
		<dt class="col-sm-3">创建时间:</dt>
		<dd class="col-sm-9">${showcaseMemberProfile.createTime?string('yyyy-MM-dd HH:mm:ss')}</dd>
		<dt class="col-sm-3">修改时间:</dt>
		<dd class="col-sm-9">${showcaseMemberProfile.updateTime?string('yyyy-MM-dd HH:mm:ss')}</dd>
		<dt class="col-sm-3">备注:</dt>
		<dd class="col-sm-9">${showcaseMemberProfile.comments}</dd>
	</dl>
</div>
