<div class="card-body">
	<dl class="row">
		<dt class="col-sm-3">ID:</dt>
		<dd class="col-sm-9">${showcaseMemberContact.id}</dd>
		<dt class="col-sm-3">用户编码:</dt>
		<dd class="col-sm-9">${showcaseMemberContact.memberNo}</dd>
		<dt class="col-sm-3">用户名:</dt>
		<dd class="col-sm-9">${showcaseMemberContact.username}</dd>
		<dt class="col-sm-3">手机号码:</dt>
		<dd class="col-sm-9">${showcaseMemberContact.mobileNo}</dd>
		<dt class="col-sm-3">联系电话:</dt>
		<dd class="col-sm-9">${showcaseMemberContact.phoneNo}</dd>
		<dt class="col-sm-3">邮箱:</dt>
		<dd class="col-sm-9">${showcaseMemberContact.email}</dd>
		<dt class="col-sm-3">QQ账号:</dt>
		<dd class="col-sm-9">${showcaseMemberContact.qq}</dd>
		<dt class="col-sm-3">旺旺账号:</dt>
		<dd class="col-sm-9">${showcaseMemberContact.wangwang}</dd>
		<dt class="col-sm-3">微信账号:</dt>
		<dd class="col-sm-9">${showcaseMemberContact.wechat}</dd>
		<dt class="col-sm-3">脸书账号:</dt>
		<dd class="col-sm-9">${showcaseMemberContact.facebeek}</dd>
		<dt class="col-sm-3">谷歌账号:</dt>
		<dd class="col-sm-9">${showcaseMemberContact.google}</dd>
		<dt class="col-sm-3">省:</dt>
		<dd class="col-sm-9">${showcaseMemberContact.province}</dd>
		<dt class="col-sm-3">市:</dt>
		<dd class="col-sm-9">${showcaseMemberContact.city}</dd>
		<dt class="col-sm-3">区:</dt>
		<dd class="col-sm-9">${showcaseMemberContact.district}</dd>
		<dt class="col-sm-3">邮政编码:</dt>
		<dd class="col-sm-9">${showcaseMemberContact.zip}</dd>
		<dt class="col-sm-3">地址:</dt>
		<dd class="col-sm-9">${showcaseMemberContact.address}</dd>
		<dt class="col-sm-3">公司名:</dt>
		<dd class="col-sm-9">${showcaseMemberContact.companyName}</dd>
		<dt class="col-sm-3">职业:</dt>
		<dd class="col-sm-9">${showcaseMemberContact.career}</dd>
		<dt class="col-sm-3">创建时间:</dt>
		<dd class="col-sm-9">${showcaseMemberContact.createTime?string('yyyy-MM-dd HH:mm:ss')}</dd>
		<dt class="col-sm-3">修改时间:</dt>
		<dd class="col-sm-9">${showcaseMemberContact.updateTime?string('yyyy-MM-dd HH:mm:ss')}</dd>
		<dt class="col-sm-3">备注:</dt>
		<dd class="col-sm-9">${showcaseMemberContact.comments}</dd>
	</dl>
</div>
