<div class="card-body">
	<dl class="row">
		<dt class="col-sm-3">主键ID:</dt>
		<dd class="col-sm-9">${shopTrackLog.id}</dd>
		<dt class="col-sm-3">访客ID（浏览器唯一标识，localStorage）:</dt>
		<dd class="col-sm-9">${shopTrackLog.visitorId}</dd>
		<dt class="col-sm-3">会话ID（单次访问会话）:</dt>
		<dd class="col-sm-9">${shopTrackLog.sessionId}</dd>
		<dt class="col-sm-3">页面类型：home/category/product/other:</dt>
		<dd class="col-sm-9">${shopTrackLog.pageType}</dd>
		<dt class="col-sm-3">页面标识：URL或页面唯一Key:</dt>
		<dd class="col-sm-9">${shopTrackLog.pageKey}</dd>
		<dt class="col-sm-3">商品ID（商品页时必填，其他页面为NULL）:</dt>
		<dd class="col-sm-9">${shopTrackLog.productId}</dd>
		<dt class="col-sm-3">停留时间（毫秒）:</dt>
		<dd class="col-sm-9">${shopTrackLog.stayDuration}</dd>
		<dt class="col-sm-3">语言代码：zh_CN/en_US/it_IT/ja_JP/ko_KR/fr_FR:</dt>
		<dd class="col-sm-9">${shopTrackLog.locale}</dd>
		<dt class="col-sm-3">浏览器UA:</dt>
		<dd class="col-sm-9">${shopTrackLog.userAgent}</dd>
		<dt class="col-sm-3">IP地址:</dt>
		<dd class="col-sm-9">${shopTrackLog.ipAddress}</dd>
		<dt class="col-sm-3">来源页面:</dt>
		<dd class="col-sm-9">${shopTrackLog.referer}</dd>
		<dt class="col-sm-3">设备类型：desktop/mobile/tablet:</dt>
		<dd class="col-sm-9">${shopTrackLog.deviceType}</dd>
		<dt class="col-sm-3">浏览器：Chrome/Firefox/Safari:</dt>
		<dd class="col-sm-9">${shopTrackLog.browser}</dd>
		<dt class="col-sm-3">来源:</dt>
		<dd class="col-sm-9">${shopTrackLog.source}</dd>
		<dt class="col-sm-3">访问日期（用于分区和统计，格式：YYYY-MM-DD）:</dt>
		<dd class="col-sm-9">${(shopTrackLog.visitDate?string('yyyy-MM-dd'))!}</dd>
		<dt class="col-sm-3">创建时间:</dt>
		<dd class="col-sm-9">${(shopTrackLog.createTime?string('yyyy-MM-dd HH:mm:ss'))!}</dd>
		<dt class="col-sm-3">update_time:</dt>
		<dd class="col-sm-9">${(shopTrackLog.updateTime?string('yyyy-MM-dd HH:mm:ss'))!}</dd>
	</dl>
</div>
